apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello-world
  name: hello-world
spec:
  containers:
  - image: fiunchinho/codely-docker:latest
    name: hello-world
    ports:
    - containerPort: 80
    resources: 
      limits:
        memory: "32Mi"
        cpu: "50m"
      requests:
        memory: "32Mi"
        cpu: "50m"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
